### ISSUE TITLE
Add support for searching arrays

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/SONG#121]
if searching a key that holds an array of text, if one or more of the elements matches the search, then the analysis is a result. Also, should there be an option to target a specific index? for instance, the SearchTerm is the following
"donors#0.address.city=toronto"

Imported from: https://jira.oicr.on.ca/browse/DCC-5690

**Comment by andricDu** [comment]
Advanced searching will be delegated to elasticsearch.
