### ISSUE TITLE
Widen infoSearch capability

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/SONG#123]
Update infoSearch to search ALL info for all id_types and return analysisIds.

if id_type is Analysis, SequencingRead or VariantCall, then return analysisId
if id_type is other, then cross reference (depending on id_type) and retried the analysis id

if Sample and Specimen meet the search criteria and have same analysisId, should they be aggregated together? if the -i is missing, then there will be repeated analysisId values.

InfoSearchResponse need to be defined.
h1. Proposed solution

if have
|crossReferenced_AnalysisId|id|id_type|info|
|A1|SA1|Sample|\{"data" : 1}|
|A1|SP1|Specimen|\{"data" : 2}|
|A1|SA2|Specimen|\{"data" : 3}|
|A2|SA3|Sample|\{"data" : 4}|

and you search for "data=.*" (so all 4 rows get hit)
```
[
  {
    "analysisId" : "A1",
    "hits" : [
      {
        "id_type" : "Sample",
        "id" : "SA1",
        "info" : {
          "data" : 1
        }
      },
      {
        "id_type" : "Specimen",
        "id" : "SP1",
        "info" : {
          "data" : 2
        }
      },
      {
        "id_type" : "Sample",
        "id" : "SA2",
        "info" : {
          "data" : 3
        }
      }
    ]
  },
  {
    "analysisId" : "A2",
    "hits" : [
      {
        "id_type" : "Sample",
        "id" : "SA3",
        "info" : {
          "data" : 4
        }
      }
    ]
  }
]
```
Imported from: https://jira.oicr.on.ca/browse/DCC-5692

**Comment by rtisma** [comment]
Related to #227 and #220

**Comment by andricDu** [comment]
Delegated to elasticsearch.
