### ISSUE TITLE
Multiple save error

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/SONG#124]
when you save an uploadId more than once, you get the error:
UploadId UP-0457ea44-4c67-4cca-b030-ac87dafb2d2d is in state 'SAVED', but must be in state 'VALIDATED' before it can be saved"
happends because logic checks for equals match for VALIDATED, instead, should use ordinals and make sure is > VALIDATED

Imported from: https://jira.oicr.on.ca/browse/DCC-5707

**Comment by rtisma** [comment]
this already fixed
