### ISSUE TITLE
Add functionality to correct an analysis, as well as Tests

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/SONG#126]
## Background
Was working with Hardeep, and accidentally saved an analysisId (which is fixed for icgc and cannot be random) with incorrect data for the experiment. She uploaded the corrections, and resaved, however, an error occurred, since an analysis with the same analysisId already exists.

## Problem
Since the updateAnalysis endpoint was commented out, need to delete analysis. There is no delete analysis endpoint, and if so, how would you handle the donors, specimens, files, sample associated with the analysis? Also, if you suppress an analysis, you cannot save the new uploaded analysis with the same analsysiId. All these issues are due to the recent "analysisId" update for the payloads

## Solution
Enable updateAnalysis endpoint, however only update fields not related to id generation. For instance, specimenId = id_function(studyId, submitterSpecimenId), fileId = id_function(analysisId, fileName), ie business keys are arguments to id_functions. If a "business key" changes, and error should be thrown, telling the user the update cannot be carried out, however any other field will be updated.  With this approach, rules need to be made regarding the handling of donor, specimens, samples and files. Imagine the analysis is changed months after being saved, and there are several other analyses using the same donor, specimens, samples...etc. Deleting a donor, implies "cascading" the effect to other analyses that use the same donor. If you delete the donor, you delete the analysis. An analysis must have one or more samples, so analysis8392 uses sampleA, and you delete sampleA, therefore analysis8392 gets deleted. This "cascading" effect is not tested

Imported from: https://jira.oicr.on.ca/browse/DCC-5751

**Comment by rtisma** [comment]
fixed with analysisType registration
