### ISSUE TITLE
Update JsonSchemas and Postrgres Schemas for optional fields

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/SONG#127]
## Background
The non-info fields of the Donor, Specimen, Sample, File and Analysis entities are not nullable. If they are not defied, they store an empty string in postgres. In addition, the JsonSchemas that define variantCalls and sequencingReads have these fields as required

## Problem
After hit a corner case with EGA, some analysis are missing values. For instance, not all EGA files have "insertSize" defined. Since insertSize is an integer, cannot make it -1 (as that would symbolize a deletion), and using a negative sentinel (like -999, -777, -888 etc) is  just wrong. InsertSize is mandatory. Other string fields cannot be assigned null, from the json payload. 

Following fields are should be REQUIRED (all others are optional):

Specimen:
* specimenType
* specimenClass
* specimenSubmitterID

Donor:
* donorSubmitterId
* donorGender

Sample:
* sampleSubmitterId
* sampleType

SequencingRead.Experiment:
* libraryStrategy

VariantCall.Experiment:
* matchedNormalSampleSubmitterId
* variantCallingTool

NOTE: if not sure if something should be required or optional, make it required. Its better to loosen an already tight system, than tighten a loose system. Imagine if external scripts used song when it was loose, and then it was tightened by making some fields REQUIRED...those scripts would break. 

## Solution
At JsonSchema level, there are 2 rules
1. if field is REQUIRED, JsonSchema must reflect that, ensure non null values
2. if field is OPTIONAL, JsonSchema must not put it in the required list. If the field is defined, it cannot be null because JsonSchema does not support null. If it is undefined, under the hood, it is regarded as null (this is needed for next part which is the postgres part)

As the Postgres level, there are 2 rules:
1. if field is REQUIRED, cannot be null
2. if field is OPTIONAL, can be null

At song level, there are 2 rules:
1. if field is REQUIRED, ensure the field in the entity is @NonNull 
2. if field is OPTIONAL, field in entity should be nullable, and proper use of Optional should be used throughout the code.

Imported from: https://jira.oicr.on.ca/browse/DCC-5752

**Comment by rtisma** [comment]
already fixed
