### ISSUE TITLE
Support synchronization between different SONG servers

### ISSUE THREAD

**Issue by junjun-zhang** [overture-stack/SONG#142]
When two (or more) SONG servers are set up to be mirroring each other (although may be not full mirroring), there would be a need to performance synchronization between them.

One real world example is ICGC data in Collab and AWS. When one SONG server is uploaded with a new Analysis object, and submitter wants it to be sync'd with AWS, the synchronization support will be helpful here.

**Comment by andricDu** [comment]
Will be handled by ICGC ARGO platform.
