### ISSUE TITLE
Prepare second batch of metadata for DKFZ PCAWG data objects

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/SONG#166]

**Comment by junjun-zhang** [comment]
Second batch of metadata sent via Slack to DKFZ

**Comment by junjun-zhang** [comment]
Not related to batch 2, but for batch 1.
Informed DKFZ to remove `wgs/b86ec8ef-d3d7-4bc6-a11a-8692d54c3d75.PRAD-UK.A34-0022_CRUK_PC_0022.A34E-0022_CRUK_PC_0022_M4.WGS-BWA-Tumor.json` from batch 1 due to this finding: https://github.com/icgc-dcc/dcc-portal/issues/459
