### ISSUE TITLE
Swagger cannot process GET /search/info multiple search terms

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#170]
when the `searchTerms` field contains   
`key1=value1&key2=value2`

expected request is
`GET /search/info?includeInfo=true&key1=value1&key2=value2`

actual request is
`GET /search/info?includeInfo=true&searchTerms=key1%3Dvalue1%26key2%3Dvalue2`

**Comment by rosibaj** [comment]
@rtisma  Is this issue still valid?

**Comment by rtisma** [comment]
invalid now that search/info endpoint was removed
