### ISSUE TITLE
Modelling of Normal Submitted Sample ID is incorrect

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#183]
Currently, to get the matchedNormalSubmittedSampleID, the donorId is extracted from the PortalFileMetadata, then the corresponding PortalDonorMetadata is retireved using that donorId from the DonorDao. In side the PortalDonorMetadata, the list of Specimens is traversed, and if `Specimen.specimenClass` contains `.*normal.*` case insensitive, then the first one that matches this criteria is considered the normal Specimen. From this all info is extract

also getMatchedNormalSubmittedSampleId is mapped to getNormalAnalysisId()
https://github.com/overture-stack/SONG/blob/develop/song-importer/src/main/java/org/icgc/dcc/song/importer/parser/NormalSpecimenParser.java

https://github.com/overture-stack/SONG/blob/develop/song-importer/src/main/java/org/icgc/dcc/song/importer/download/fetcher/DonorFetcher.java#L72

https://github.com/overture-stack/SONG/blob/develop/song-importer/src/main/java/org/icgc/dcc/song/importer/convert/AnalysisConverter.java#L162

**Comment by rtisma** [comment]
The current solutions can be explained with an example:
1. Download and load the Pcawg Sample Sheet TSV file from: http://pancancer.info/data_releases/latest/pcawg_sample_sheet.tsv

2. For the file [FI743097](https://dcc.icgc.org/repositories/files/FI743097) extract the following info:
    * donorId ([DO46877](https://dcc.icgc.org/donors/DO46877))
    * dccProjectCode ([RECA-EU](https://dcc.icgc.org/projects/RECA-EU))
    * libraryStrategy (RNA-Seq)

3. Filter the Pcawg Sample Sheet for the above donorId, dccProjectCode, libraryStrategy, which should return **ONLY 2 RESULTS** (this is the assumption):

| icgc_donor_id | dcc_project_code | library_strategy | icgc_sample_id | dcc_specimen_type                   |
|---------------|------------------|------------------|----------------|-------------------------------------|
| DO46877       | RECA-EU          | RNA-Seq          | SA507317       | Primary tumour - solid tissue       |
| DO46877       | RECA-EU          | RNA-Seq          | SA507320       | Normal - tissue adjacent to primary |

4. Filter the previous 2 results, for the result that contains the **case-insensitive** value `normal` for the dcc_specimen_type, which should have **ONLY 1 result**:

| icgc_donor_id | dcc_project_code | library_strategy | icgc_sample_id | dcc_specimen_type                   |
|---------------|------------------|------------------|----------------|-------------------------------------|
| DO46877       | RECA-EU          | RNA-Seq          | SA507320       | Normal - tissue adjacent to primary |

5. From that result, the **matchedNormalSubmitterSampleId** for the file [FI743097](https://dcc.icgc.org/repositories/files/FI743097) is therefore `SA507320`


@junjun-zhang  please confirm this example models the search matchedNormalSubmitterSampleId process given a fileId

**Comment by junjun-zhang** [comment]
@rtisma We don't have somatic variants called from RNA-Seq data, so more realistic example would be using WGS. Other than that, the process is fine.

Keep in mind, this is only applicable to somatic variant VCF entries.

**Comment by rtisma** [comment]
@junjun-zhang ok thanks. I chose a file that had a donor with PCAWG and NON-PCAWG samples, as a worst case example. I am only processing VCF files (VariantCallAnalysis) as they are the only ones with the `matchesNormalSubmitterSampleId`

**Comment by rtisma** [comment]
both aws and collab databases have been updated with the corrected VariantCalls (846 for aws, 862 for collab). 

## AWS
Search for the analysisId `3f065266-4c35-4b65-a49e-c6bffd81bf86` using [swagger-ui](https://virginia.song.icgc.org/swagger-ui.html) `ReadAnalysis` endpoint:
* MatchedNormalSubmitterSampleId **Before**: `010-02-1ND`
* MatchedNormalSubmitterSampleId **After**: `010-0028-07ND`
* DB dump before change: `before_fixing_matched_normal.song_aws_virginia_db_backup.20180221_173043_UTC.sql.gz`

## Collab
Search for the analysisId `840b069a-4fc8-412d-b7b4-c63d63502cb5` using [swagger-ui](https://song.cancercollaboratory.org/swagger-ui.html) `ReadAnalysis` endpoint:
* MatchedNormalSubmitterSampleId **Before**: `PD4607b2`
* MatchedNormalSubmitterSampleId **After**: `PD4607b`
* DB dump before change: `before_fixing_matched_normal.song_db_dump.20180221_172145_UTC.sql.gz`

This issue is now fixed and will be closed

**Comment by rtisma** [comment]
related to #196 also
