### ISSUE TITLE
Update Importer to just generate Upload Payloads

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#185]
the current importer is too complicated with all the rules. Before, since analysisIds could not be user submitted, we had to backdoor the database, which meant manually maintaining entity relationships in the importer. Now that analysisIds can be user submitted we can generate payloads and load song from the front, and let song do that entity relationship management properly

In terms of maintaining donorIds, sampleIds ..etc that match what dcc-portal uses, since song would use id.icgc.org, which is also used in generating data for dcc-portal, the ids would be the same.

the importer would just generate payloads locally, and then song would batch upload them

**Comment by andricDu** [comment]
importer is dead. RIP in pepperoni.
