### ISSUE TITLE
Add rolling cleanup to db backups

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#190]
Currently, backups of the postgres db are done every night at midnight. There is no cleanup. After a year, there will be too many backups, that would possibly be outdated.

Need to cleanup (aka delete) old backups. Related to Issue rtisma/postgres-to-s3-backup#2

**Comment by andricDu** [comment]
Assigning to @jonathanganesh to help out.

**Comment by rtisma** [comment]
Assigning back to me, since this will require the python code to be modified.

**Comment by andricDu** [comment]
infra
