### ISSUE TITLE
Provision Postgres DB logging configuration

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#194]
https://www.endpoint.com/blog/2012/06/30/logstatement-postgres-all-full-logging

After a system is put into production and uses postgres, sometimes there are issues at the beginning, and having postgres log the data would be beneficial. Would be very nice to have an ansible script to provision 2 modes: performance and monitor mode. Monitor mode would have all the debug and logging set. Performance would have the default.

**Comment by rtisma** [comment]
```
log_statement = 'all'
log_connections = on
log_disconnections = on
log_duration = on
log_min_duration_statement = -1
```
was set on song.cancercollaboratory.org's postgres server, so now there will be more verbosity

**Comment by rtisma** [comment]
removed from Spring 183, because there is no skeleton provisioning for song yet. Before the database can be provisioned, song installation and configuration must be provisioned first.

**Comment by andricDu** [comment]
Infrastructure.
