### ISSUE TITLE
Missing index files from song.collab for FI206869

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#199]
The file FI206869 has objectId 
5b91da7b-379d-5beb-9d2f-953795e9024c

and submitter bundle id

fe1bd829-6d0f-45c3-8594-85d4d5d13d49

if you do 
https://song.cancercollaboratory.org/entities/1249a65b-2d4b-5610-a981-e4a8604f862a

you get a file not found error, however you retrieve the correct response when you do

https://meta.icgc.org/entities/1249a65b-2d4b-5610-a981-e4a8604f862a

**Comment by junjun-zhang** [comment]
Looked all the way back into original source of this file: https://gtrepo-riken.annailabs.com/cghub/metadata/analysisFull/fe1bd829-6d0f-45c3-8594-85d4d5d13d49

There is no `.bai` file!

**Comment by junjun-zhang** [comment]
The fix is to download the BAM file and generate BAI, then upload to icgc storage, lastly update SONG metadata to include the new BAI.

The BAI file name should be: PCAWG.5f66b9a6-e1f3-11e4-8f30-aabb917fcde1.STAR.v1.bam.bai

**Comment by rtisma** [comment]
ok thank @junjun-zhang, closing this ticket since we know what the issue is and how to fix it. 

As a temporary fix for the storage-client, if the user encounters this issue with other files, all they have to todo is add the switch `--index false` to their icgc-storage-client download command, and downloading of the accompanying index file will be skipped.

**Comment by junjun-zhang** [comment]
Identified 106 PCAWG `vcf.gz` files missing index files, see attached file: 
[vcf_missing_index.all_projects.tar.gz](https://github.com/overture-stack/SONG/files/1925292/vcf_missing_index.all_projects.tar.gz)
