### ISSUE TITLE
Users should not be able to ignore_analysis_id_collisions

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#207]
Minimally invasive solution is to add the field to the application.yml for the song server, and only allow it to be enable/disable at server run time, and remove it from the endpoint for saving an analysis. Therefore, when doing an import, start the server with it enabled, do the import, then restart the server with it disabled.

**Comment by rtisma** [comment]
Better solution would be to only allow users with the scope `<prefix>.admin.upload` to override analysisId collisions.  a warning log should be output indicating this, and the activation of this feature should be logged when this scope is used.

**Comment by rosibaj** [comment]
@rtisma is this issue still valid?

**Comment by rtisma** [comment]
invalid now that analysisIds are randomly generated and cannot be assigned by a user
