### ISSUE TITLE
Perform check on all SONG analysis to verify index file exist for BAM and VCF files

### ISSUE THREAD

**Issue by junjun-zhang** [overture-stack/SONG#209]
It's been reported BAI may be missing in SONG metadata: https://github.com/overture-stack/SONG/issues/199. In this particular case the root cause was that BAI was missing in GNOS.

We need to thoroughly check whether there are any other such instances.

**Comment by junjun-zhang** [comment]
Naming conventions for index files:
- BAM file: {bam_file_name}.bam.bai
- VCF file, vcf file itself is usually ended with `.vcf.gz`. Two possible index file extensions are allowed:
 -- TBI: {vcf_file.vcf.gz}.tbi
 -- IDX: {vcf_file.vcf.gz}.idx

**Comment by junjun-zhang** [comment]
@rtisma, is there a way to download SONG metadata in bulk? GNOS has a feature allowing user to pull down trimmed version of metadata from search result. For example, if a search resulted in 5 analysis objects, user will be able to get metadata for the list of 5 entries each with selected set of fields (eg, file name, file size, file md5sum, sample, study etc).

That was very useful, do we have something similar in SONG?

**Comment by rtisma** [comment]
@junjun-zhang the search capability of song from the start was intended to be minimal. Adding additional search functionality was not an initial priority, so a minimal search api was provided allowing the user to search analyses using info fields and entity ids. I believe if we were to implement search beyond the capabilities of what we currently have, we would probably use elasticsearch, similar to how portal does it. From there, we would be able to create a specialized search api for song, that would use elasticsearch in the backend, and not a database (as it is currently).

**Comment by junjun-zhang** [comment]
Thanks @rtisma, querying using REST API is pretty good. Something like this `curl -X GET --header 'Accept: application/json' 'https://song.cancercollaboratory.org/studies/PACA-CA/analysis'` works well for what I need.

**Comment by junjun-zhang** [comment]
Identified 106 PCAWG vcf.gz files missing index files, see attached file:
[vcf_missing_index.all_projects.tar.gz](https://github.com/overture-stack/SONG/files/1926157/vcf_missing_index.all_projects.tar.gz)

There are many bam files do not have index files, but almost all of them are non-PCAWG except for the one reported here: PCAWG.5f66b9a6-e1f3-11e4-8f30-aabb917fcde1.STAR.v1.bam.bai. For the non-PCAWG bam, most of them are unaligned BAMs, so bai is not applicable.
