### ISSUE TITLE
Improve health API for monitoring 

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#210]
there should be a new health api endpoint, that not only checks if song is running (like the ping), but checks database connectivity, auth server running, and id server running, available disk space, reach able hosts, etc

**Comment by rtisma** [comment]
Postgres: https://github.com/docker-library/healthcheck/blob/master/postgres/docker-healthcheck

**Comment by andricDu** [comment]
Revisit later if needed due to monitoring of pods in Kubernetes.
