### ISSUE TITLE
Update SONG Jenkins to run a postgres docker container before testing 

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#234]
Currently having a postgres cache issue (issue #125 ) as shown in https://dcc-jenkins.oicr.on.ca/job/song-pr/301/console

by creating a new docker container everytime on the same port, when the song tests are run by maven, a fresh new postgres server will be used, possibly eliminating issue #125 . The postgres docker container should have the username `postgres` with password `password` and on some port (could be static or random), and intialized by creating the database `test_db`. The database can be created using the following command:
```bash
PGPASSWORD=password psql -h localhost -p <postgres-port> -U postgres postgres -c "CREATE DATABASE test_db;"
```

To configure spring to override the database url, the following should be done:
```bash
echo "spring.datasource.url=jdbc:postgresql://localhost:<postgres-port>/test_db?stringtype=unspecified" > song/song-server/src/main/resources/application-dev.properties
echo "spring.datasource.username=postgres" >> song/song-server/src/main/resources/application-dev.properties
echo "spring.datasource.password=password" >> song/song-server/src/main/resources/application-dev.properties
``` 
then to test run:
`mvn test`

**Comment by andricDu** [comment]
will be handled by testcontainers.
