### ISSUE TITLE
Schema anomalies detected 

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#251]
After running [SchemaSpy](http://schemaspy.sourceforge.net/) with the command
```bash
java -jar schemaSpy_5.0.0.jar -u rtisma -noschema -host localhost -t pgsql -db song -dp postgresql-42.2.2.jar  -o song-schema-spy-output
```
the following anomalies were detected

<img width="904" alt="screen shot 2018-03-16 at 1 01 20 pm" src="https://user-images.githubusercontent.com/942951/37534236-ad4bec2e-291a-11e8-9421-08565647c9fe.png">

**Comment by andricDu** [comment]
Depending on flyway migrations.

**Comment by rosibaj** [comment]
Closing as this issue is no longer vallid - next release of song will enable dyanmic schemas.
