### ISSUE TITLE
SONG save error involving ID that already exists

### ISSUE THREAD

**Issue by hknahal** [overture-stack/SONG#290]
- Attempting to publish SONG payloads for "potato" donors (https://github.com/icgc-dcc/dcc-portal/issues/452)
- SONG generates an error when attempting to save an upload ID.

**Payload used in this example:** https://github.com/hknahal/song_payloads_missing_pcawg_metadata/blob/master/DO218091/02437ae6-d281-11e5-b76e-e3105c6878de.json
Related to file from PAEN-AU project: https://dcc.icgc.org/repositories/files/FI332924

**1. Upload Payload:**

sing upload -f 02437ae6-d281-11e5-b76e-e3105c6878de.json
`{"status":"ok","uploadId":"UP-b9b90ab1-98c0-4e59-b92e-36a4f6e23d24"}`

**2. Save Payload**

sing save -u UP-b9b90ab1-98c0-4e59-b92e-36a4f6e23d24

_Returns error:_

`SONG_SERVER_ERROR[analysis.id.collision @ 1528137372045]: [IdService::analysis.id.collision] - Collision detected for analysisId '02437ae6-d281-11e5-b76e-e3105c6878de'. To ignore collisions, rerun with ignoreAnalysisIdCollisions = true`

--> Try with `ignoreAnalysisIdCollisions` flag:

sing save -u UP-b9b90ab1-98c0-4e59-b92e-36a4f6e23d24 -i

_Returns error:_
`SONG_SERVER_ERROR[info.already.exists @ 1528140171463]: [FileInfoService::info.already.exists] - Could not create Info record for id='a60cf466-d8a6-569a-8639-d5c81ee37e29' and type='File' because it already exists`

**Comment by junjun-zhang** [comment]
The metadata XML file `02437ae6-d281-11e5-b76e-e3105c6878de.xml` appeared four times in the SONG payload: https://github.com/hknahal/song_payloads_missing_pcawg_metadata/blob/master/DO218091/02437ae6-d281-11e5-b76e-e3105c6878de.json

This is certainly an error. The reported error message was somewhat close but not very specific.

**Comment by hknahal** [comment]
This issue has been resolved. The redundant files were removed from the affected SONG payloads and were successfully uploaded and published
