### ISSUE TITLE
Saving the same uploadId mutliple times without changes gives a different analysisId

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#307]
If you do an upload, and save that upload id twice one after another, you get back 2 different analysisIds (given that the analysisId is not defined in the payload). The database should have a new column in the upload table called `is_saved`, and if the uploadId is saved, that field should be true. After a successful save of an uploadId, if another save is called on that same uploadId, since the `is_saved` field is true, an error should be thrown. You cannot update an uploadId after saving. The same applies for when the analysisId is baked into the payload.

**Comment by andricDu** [comment]
@rtisma can you give @blabadi some background. Also you misspelled "High" :full_moon_with_face:

**Comment by andricDu** [comment]
Talked to @rtisma , ticket no longer valid.
