### ISSUE TITLE
Add 'study' field in SONG payload and make it required

### ISSUE THREAD

**Issue by junjun-zhang** [overture-stack/SONG#308]
There are two major benefits for 'study' to be added to the SONG payload:
* prevent user from (accidentally) uploading analysis object to a wrong study, if happened it could end up with leaking controlled data to unauthorized clients. Also, such mistake can easily go through silently, so it would be the best to prevent it in the first place
* it's useful to keep track of payload on user's end when there are many SONG payloads to be generated/managed

**Comment by hknahal** [comment]
Here's an example of two different projects (mistakenly) assigned to the same file:  https://dcc.icgc.org/repositories/files/FI35779
