### ISSUE TITLE
Create Half-Song for PDC

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#316]
after some discussion, the simplest method for presenting PDC metadata in portal, is to set up a song PDC server, which is not connected to a score-server (hence half-song). The song pdc server would only be able to save, which would be enough for the bioinfo team as they need a place to store metadata, and therefore publishing would not be possible. 

need to create a collab VM, with song and postgres installed and configured. Need to have firewall rules inplace since it will only be used internally and no TLS (or create self signed). Should be tied to auth.icgc.org just for added security and the `collab.download` and `collab.upload` scopes should be used for tokens.

**Comment by d8660091** [comment]
https://song-docs.readthedocs.io/en/develop/server.html
