### ISSUE TITLE
Update dcc-repository with override flag for indexing UNPUBLISHED data

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#317]
Currently, portal only indexes PUBLISHED song metadata. To accommodate  #316 , a flag must be implemented that allows portal to index data that is UNPUBLISHED since there is a half-song

**Comment by Fgerthoffert** [comment]
Planning discussion: will break the metadata in multiple payloads, @junjun-zhang will create corresponding ticket for the bioinformatics team.

**Comment by rtisma** [comment]
@junjun-zhang is the plan still to have dcc portal index the half-song  PDC metadata?

**Comment by rtisma** [comment]
fixed in icgc-dcc/dcc-repository#27
