### ISSUE TITLE
Internal Server Error when trying to save upload ID

### ISSUE THREAD

**Issue by hknahal** [overture-stack/SONG#319]
SONG payload is "validated": https://song.cancercollaboratory.org/upload/BOCA-FR/status/UP-ad0f1faa-36f9-45b8-a13f-b7e85e63b527

But when trying to save the upload, the following error is returned:

Traceback (most recent call last):
  File "/scripts//upload", line 100, in <module>
    main()
  File "/scripts//upload", line 70, in main
    raise e
  File "/scripts//upload", line 66, in main
    api.save(upload_status.uploadId, ignore_analysis_id_collisions=True)
  File "/usr/local/lib/python3.6/dist-packages/overture_song/client.py", line 66, in save
    return self.__rest.post(endpoint)
  File "/usr/local/lib/python3.6/dist-packages/overture_song/rest.py", line 85, in post
    return self._intercept(requests.post)(url, json=dict_data, headers=self.__header_generator.get_json_header())
  File "/usr/local/lib/python3.6/dist-packages/overture_song/rest.py", line 55, in new_function
    raise song_error
overture_song.model.SongError: {
    "errorId": "unknown.error",
    "httpStatusName": "INTERNAL_SERVER_ERROR",
    "httpStatusCode": 500,
    "message": "java.io.IOException: Stream closed",
    "requestUrl": "http://song.cancercollaboratory.org/upload/BOCA-FR/save/UP-ad0f1faa-36f9-45b8-a13f-b7e85e63b527?ignoreAnalysisIdCollisions=True",
    "debugMessage": "[ROOT_CAUSE] -> java.io.IOException: Stream closed",
    "timestamp": 1536264033403,
    "stackTrace": [
        "com.sun.jersey.api.client.ClientHandlerException: java.io.IOException: Stream closed",
        "at com.sun.jersey.client.apache.DefaultApacheHttpMethodExecutor.executeMethod(DefaultApacheHttpMethodExecutor.java:213)",
        "at com.sun.jersey.client.apache.ApacheHttpClientHandler.handle(ApacheHttpClientHandler.java:175)",
        "at com.sun.jersey.api.client.Client.handle(Client.java:648)",
        "at org.icgc.dcc.id.client.http.webclient.WebClientFactory$1.handle(WebClientFactory.java:97)",
        "at com.sun.jersey.api.client.Client.handle(Client.java:648)",
        "at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680)",
        "at com.sun.jersey.api.client.WebResource.get(WebResource.java:191)",
        "at org.icgc.dcc.id.client.http.HttpIdClient.getResponse(HttpIdClient.java:314)",
        "at org.icgc.dcc.id.client.http.HttpIdClient.getResponse(HttpIdClient.java:309)",
        "at org.icgc.dcc.id.client.http.HttpIdClient.getAnalysisId(HttpIdClient.java:157)",
        "at org.icgc.dcc.id.client.http.HttpIdClient.getAnalysisId(HttpIdClient.java:104)",
        "at org.icgc.dcc.song.server.service.IdService.resolveAnalysisId(IdService.java:94)",
        "at org.icgc.dcc.song.server.service.AnalysisService.create(AnalysisService.java:139)",
        "at org.icgc.dcc.song.server.service.AnalysisService$$FastClassBySpringCGLIB$$f0f60456.invoke(<generated>)",
        "at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)",
        "at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)",
        "at org.icgc.dcc.song.server.service.AnalysisService$$EnhancerBySpringCGLIB$$52fc6048.create(<generated>)",
        "at org.icgc.dcc.song.server.service.UploadService.save(UploadService.java:159)",
        "at org.icgc.dcc.song.server.service.UploadService$$FastClassBySpringCGLIB$$e7fea8d1.invoke(<generated>)",
        "at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)",
        "at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)",
        "at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)",
        "at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)",
        "at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)",
        "at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)",
        "at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)",
        "at org.icgc.dcc.song.server.service.UploadService$$EnhancerBySpringCGLIB$$ec577299.save(<generated>)",
        "at org.icgc.dcc.song.server.controller.UploadController.save(UploadController.java:95)",
        "at org.icgc.dcc.song.server.controller.UploadController$$FastClassBySpringCGLIB$$c808fb25.invoke(<generated>)",
        "at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)",
        "at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)",
        "at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)",
        "at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)",
        "at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)",
        "at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)",
        "at org.icgc.dcc.song.server.controller.UploadController$$EnhancerBySpringCGLIB$$f0193bd6.save(<generated>)",
        "at sun.reflect.GeneratedMethodAccessor245.invoke(Unknown Source)",
        "at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "at java.lang.reflect.Method.invoke(Method.java:498)",
        "at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)",
        "at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)",
        "at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)",
        "at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)",
        "at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)",
        "at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)",
        "at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)",
        "at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)",
        "at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)",
        "at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)",
        "at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)",
        "at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)",
        "at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
        "at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
        "at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:158)",
        "at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:126)",
        "at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:111)",
        "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
        "at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:84)",
        "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
        "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)",
        "at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)",
        "at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)",
        "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
        "at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)",
        "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
        "at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)",
        "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
        "at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)",
        "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
        "at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)",
        "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
        "at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)",
        "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
        "at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176)",
        "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
        "at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)",
        "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
        "at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)",
        "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
        "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
        "at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)",
        "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
        "at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)",
        "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
        "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
        "at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)",
        "at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)",
        "at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)",
        "at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
        "at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)",
        "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
        "at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)",
        "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
        "at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)",
        "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
        "at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)",
        "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
        "at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)",
        "at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)",
        "at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)",
        "at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)",
        "at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)",
        "at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)",
        "at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)",
        "at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)",
        "at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)",
        "at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)",
        "at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)",
        "at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)",
        "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
        "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
        "at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)",
        "at java.lang.Thread.run(Thread.java:748)",
        "Caused by: java.io.IOException: Stream closed",
        "at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)",
        "at java.io.BufferedInputStream.fill(BufferedInputStream.java:214)",
        "at java.io.BufferedInputStream.read(BufferedInputStream.java:265)",
        "at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)",
        "at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)",
        "at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)",
        "at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)",
        "at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)",
        "at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)",
        "at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)",
        "at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)",
        "at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)",
        "at com.sun.jersey.client.apache.DefaultApacheHttpMethodExecutor.executeMethod(DefaultApacheHttpMethodExecutor.java:210)",
        "... 130 more",
        ""
    ]
}
Traceback (most recent call last):
  File "/home/ubuntu/jthome/account.7187010b-8f2b-4a85-b9d9-106386d2dce6/node/workflow.8296e7a8-5e23-4f0b-befe-d578737ff308/0.8.42/workflow/tools/upload.py", line 32, in <module>
    '-d', '/app/'])
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'run', '--net=host', '-e', 'ACCESSTOKEN', '-e', 'STORAGEURL=https://storage.cancercollaboratory.org:443', '-e', 'METADATAURL=https://song.cancercollaboratory.org', '-v', '/home/ubuntu/jthome/account.7187010b-8f2b-4a85-b9d9-106386d2dce6/node/workflow.8296e7a8-5e23-4f0b-befe-d578737ff308/0.8.42/queue.afd828f1-0698-4c57-b8c8-47acadb8dd40/executor.20351261-2a80-4691-8286-2b51e93a6ec2/job.bc969a02-87f1-4a72-8418-f6e9df44c6ac/task.download:/app', 'quay.io/baminou/dckr_song_upload', 'upload', '-s', 'BOCA-FR', '-u', 'https://song.cancercollaboratory.org', '-p', '/app/payload.json', '-o', 'manifest.txt', '-j', 'manifest.json', '-d', '/app/']' returned non-zero exit status 1

**Comment by rtisma** [comment]
related to icgc-dcc/dcc-id#17

**Comment by rtisma** [comment]
fixed since EGAR00001222239 is published
