### ISSUE TITLE
Add go-client building with maven

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#363]
The root pom.xml should have a step to build the go-client for osx, linux and windows, using the GOOS and GOARCH env variables to build the right binaries. 

This automation should be added to as a build step. As an example, refer to 
https://github.com/raydac/mvn-golang

**Comment by rtisma** [comment]
@d8660091 I still see some things failing
https://circleci.com/gh/overture-stack/SONG/418?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by d8660091** [comment]
> @d8660091 I still see some things failing
> https://circleci.com/gh/overture-stack/SONG/418?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

@rtisma probably because 418 still use the old .circleci config, once it uses the circleci config file in the branch, it would be fixed.
