### ISSUE TITLE
incorporate test-containers for tests

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#365]
currently tests expect a local installation of postgres. Would be nice to have test-containers integration (like in overture-stack/ego). In addition, circle-ci and travis-ci should not break.

**Comment by rtisma** [comment]
is blocking #382. once testcontainers is incorporated, then can follow work done on ego

**Comment by andricDu** [comment]
This would be high value. Let me know if you need to discuss. @blabadi 

Looking for something similar to way Ego is using them.
