### ISSUE TITLE
Internal Server Error when attempting to publish SONG payload in AWS

### ISSUE THREAD

**Issue by hknahal** [overture-stack/SONG#371]
The SONG payload for analysis ID "EGAZ00001018833" is "unpublished" in AWS: https://virginia.song.icgc.org/studies/OV-AU/analysis/EGAZ00001018833

When attempting to publish it (via the SONG API), an internal error results (see further below). 

I am however able to download the controlled files in this unpublished SONG payload using score-client, indicating the files do exist in AWS (this might be related to my other ticket https://github.com/overture-stack/score/issues/128)

The same things happens for 13 other files (see top few files at https://icgc.org/ZHw). 

Error after trying to publish SONG payload:

{
  "errorId": "unknown.error",
  "httpStatusCode": 500,
  "httpStatusName": "INTERNAL_SERVER_ERROR",
  "requestUrl": "http://virginia.song.icgc.org/studies/OV-AU/analysis/publish/EGAZ00001018833?ignoreUndefinedMd5=false",
  "datetime": "2018-11-21T16:29:41.16Z[Etc/UTC]",
  "timestamp": 1542817781160,
  "message": "403 null",
  "debugMessage": "[ROOT_CAUSE] -> org.springframework.web.client.HttpClientErrorException: 403 null",
  "stackTrace": [
    "org.springframework.web.client.HttpClientErrorException: 403 null",
    "at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)",
    "at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79)",
    "at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)",
    "at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:775)",
    "at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:728)",
    "at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:702)",
    "at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:619)",
    "at bio.overture.song.server.service.StorageService.lambda$doGetString$0(StorageService.java:102)",
    "at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)",
    "at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)",
    "at bio.overture.song.server.service.StorageService.doGetString(StorageService.java:98)",
    "at bio.overture.song.server.service.StorageService.doGetBoolean(StorageService.java:108)",
    "at bio.overture.song.server.service.StorageService.isObjectExist(StorageService.java:64)",
    "at bio.overture.song.server.service.AnalysisService.confirmUploaded(AnalysisService.java:530)",
    "at bio.overture.song.server.service.AnalysisService.lambda$checkMissingFiles$7(AnalysisService.java:452)",
    "at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)",
    "at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)",
    "at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)",
    "at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)",
    "at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)",
    "at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)",
    "at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)",
    "at bio.overture.song.server.service.AnalysisService.checkMissingFiles(AnalysisService.java:453)",
    "at bio.overture.song.server.service.AnalysisService.publish(AnalysisService.java:384)",
    "at bio.overture.song.server.service.AnalysisService$$FastClassBySpringCGLIB$$7681c8ae.invoke(<generated>)",
    "at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)",
    "at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)",
    "at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)",
    "at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)",
    "at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)",
    "at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)",
    "at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)",
    "at bio.overture.song.server.service.AnalysisService$$EnhancerBySpringCGLIB$$f87b22d3.publish(<generated>)",
    "at bio.overture.song.server.controller.AnalysisController.publishAnalysis(AnalysisController.java:110)",
    "at bio.overture.song.server.controller.AnalysisController$$FastClassBySpringCGLIB$$b8162298.invoke(<generated>)",
    "at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)",
    "at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)",
    "at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)",
    "at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)",
    "at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)",
    "at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)",
    "at bio.overture.song.server.controller.AnalysisController$$EnhancerBySpringCGLIB$$5293230e.publishAnalysis(<generated>)",
    "at sun.reflect.GeneratedMethodAccessor459.invoke(Unknown Source)",
    "at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
    "at java.lang.reflect.Method.invoke(Method.java:498)",
    "at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)",
    "at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)",
    "at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)",
    "at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)",
    "at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)",
    "at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)",
    "at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)",
    "at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)",
    "at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)",
    "at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:888)",
    "at javax.servlet.http.HttpServlet.service(HttpServlet.java:664)",
    "at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)",
    "at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)",
    "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)",
    "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)",
    "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:158)",
    "at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:126)",
    "at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:111)",
    "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:84)",
    "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)",
    "at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)",
    "at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)",
    "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)",
    "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)",
    "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)",
    "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)",
    "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)",
    "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176)",
    "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)",
    "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)",
    "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)",
    "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)",
    "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)",
    "at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)",
    "at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)",
    "at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)",
    "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)",
    "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)",
    "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)",
    "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)",
    "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)",
    "at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)",
    "at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)",
    "at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)",
    "at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)",
    "at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)",
    "at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)",
    "at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)",
    "at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)",
    "at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)",
    "at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)",
    "at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)",
    "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
    "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
    "at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)",
    "at java.lang.Thread.run(Thread.java:748)",
    ""
  ]
}

**Comment by rtisma** [comment]
@hknahal can you try running this publish from an AWS vm?

**Comment by rtisma** [comment]
The same issue is happening for https://virginia.song.icgc.org/studies/OV-AU/analysis/EGAR00001083599. Reopening

**Comment by rtisma** [comment]
@hknahal i was able to publish both analysisIds, so i cannot recreate the issue. Please ensure you have `aws.upload` scope
