### ISSUE TITLE
score /download endpoint call should use application level token

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#380]
Currently, when the use the publish endpoint, we validate the file data in song with the file data in score. To get the score file data, we need to call the /download endpoint. To call this endpoint, we need download scope. The Authorization token is taken from the publish request, and then passed to the /download endpoint. Becuse of this, we require upload scope for publishing AND download scope for the score server. This is not cool.

Fix is to create another token that has download scope and it is used by song (application level) to make the /download call to score. The user should not need download scope to do a song upload.

This is related to #371 

Test case is 
user-agent call publish endpoint with `collab.upload` scope. Publish should be successful

**Comment by d8660091** [comment]
https://github.com/overture-stack/SONG/pull/381
