### ISSUE TITLE
Missing Files in Collab which used to exist recently

### ISSUE THREAD

**Issue by hknahal** [overture-stack/SONG#387]
**Case 1:**

We found a file that used to exist in Collab as recently as yesterday (Jan 21, 2019) but today it only exists in EGA: https://dcc.icgc.org/repositories/files/FI9995

The SONG payload shows the analysis is “unpublished”: https://song.cancercollaboratory.org/studies/BRCA-EU/analysis/efcf90ee-53ae-4f9f-b29a-e0a83ca70272 

There's also some extra data in the payload that didn't exist before or is incorrect. For example, the file size of the BAM file is "23" and there is some unrelated information in the “info” field which wasn’t there before:

![image](https://user-images.githubusercontent.com/4992044/51568041-cad58880-1e66-11e9-981d-cf5a0b662007.png)

**Case 2:**

There's also a similar issue with another file (it used to exist in the Portal but doesn't anymore). I'm not sure if the two cases are related but here are some details:

A downloaded manifest file from December 2018 from the Portal contained information for file ID FI808273 (analysis ID EGAR00001193006). However, the file ID FI808273 no longer exists in the Portal now (Jan 2019).

Manifest file from Dec 2018 containing FI808273:

repo_code | file_id | object_id | file_format | file_name | file_size | md5_sum | index_object_id | donor_id/donor_count | project_id/project_count | study
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
collaboratory | FI808273 | 546c33c3-068b-5bb8-bc31-fa908c5d4752 | BAM | 84d756983fe7d19d59c59c00aad2b377.SM-4AX85.bam | 161544272712 | 84d756983fe7d19d59c59c00aad2b377 |   | DO50334 | ESAD-UK |  

In JTracker, the analysis ID EGAR00001193006 exists in git repo as "completed", confirming the files were uploaded to Collab: https://github.com/icgc-dcc/ega-file-transfer/blob/daf4ce5d778cd9ca8b4dc08f40221f992a3a3e39/ega_transfer_jobs/completed-jobs/job.EGAR00001193006.ESAD-UK.SM-4AX85.EGAN00001198224/job.EGAR00001193006.ESAD-UK.SM-4AX85.EGAN00001198224.json

If I try to download the BAM file using score-client, it fails and the logs indicate the file does not exist in Collab, even though it appears to have been uploaded successfully in JTracker.

Error from score-client:
`
bio.overture.score.client.exception.NotRetryableException: java.io.IOException: Storage client error: {"timestamp":1548085504898,"status":404,"error":"Not Found","exception":"bio.overture.score.server.exception.IdNotFoundException","message":"546c33c3-068b-5bb8-bc31-fa908c5d4752","path":"/download/546c33c3-068b-5bb8-bc31-fa908c5d4752"}`

**Comment by rtisma** [comment]
@hknahal portal no longer shows unpublished analyses. in addition, I could not find the upload that was responsible for efcf90ee-53ae-4f9f-b29a-e0a83ca70272, which means it was probably created by the importer. If that is the case, then the size value of 23 could have only been changed by a user using the fileUpdate endpoint. As of the most recent score server, unpublished files cannot be downloaded anymore.
