### ISSUE TITLE
Response code = 0 when creating a study properly

### ISSUE THREAD

**Issue by vferretti** [overture-stack/SONG#394]
I created a study using the SONG Swagger interface with the following payload.
{
  "studyId": "study2",
  "name": "study2",
  "organization": "CHURSJ",
  "description": "std server instance"
}

The study was properly created but I got a 0 response code from the API (instead of 201 according to the end point specification) and the following response header: 

{
  "error": "no response from server"
}

**Comment by rtisma** [comment]
We are aware of this issue. It will be fixed once #220 is completed, as this is a breaking change

**Comment by rtisma** [comment]
fixed in #508
