### ISSUE TITLE
Investigation - SONG changes entity's submitter IDs without any warning

### ISSUE THREAD

**Issue by vferretti** [overture-stack/SONG#395]
Step 1) I created an analysis with a new trio of donor, biospecimen and sample submitter IDs: (dd1, spp1, saa1). As expected SONG created 3 new entities (DO20, SP21, SA19).
Step 2) I created a second analysis with the following submitter IDs (dd2, spp1, saa1)

Result: SONG ignored submitter ID dd2 and created the analysis with (D020, SP21, SA10). 

We would have expected instead an error message saying that a biospecimen (spp1) cannont belong to two different donors (dd1 and dd2). 

See enclosed the payload
[bug.txt](https://github.com/overture-stack/SONG/files/2872000/bug.txt)

**Comment by rtisma** [comment]
Related to #235
