### ISSUE TITLE
Fix case sensitivty in SONG

### ISSUE THREAD

**Issue by alekspejovic** [overture-stack/SONG#401]
Currently when SONG reads in a scope in the following format ("collab.abc123.WRITE") , it converts the study name (abc123) to all uppercase (ABC123). However if the study was registered in lowercase (abc123), then the message returns an unauthorized token error because the scope does not match up.

We should make all input strings case sensitive in SONG.

**Comment by alekspejovic** [comment]
Reopening since this still needs to be tested in SONG QA.

**Comment by rosibaj** [comment]
@andricDu introduced a bug where you cannot introduce a scope with a `.` in it... which broke this.  still in progress

**Comment by rtisma** [comment]
@KevinFHartmann is there a PR for this?

**Comment by KevinFHartmann** [comment]
I thought we'd merged the original into development, but that it still needed testing?
