### ISSUE TITLE
Fix error messages when authorization fails due to invalid token

### ISSUE THREAD

**Issue by alekspejovic** [overture-stack/SONG#402]
Currently , song returns an HTML error message. Error message should be in JSON format.

![image](https://user-images.githubusercontent.com/12387683/54545808-c31ef580-4978-11e9-8769-71a549fe40e7.png)

**Comment by KevinFHartmann** [comment]
Technically, I think the HTML is coming from NGINX, but we need the proper JSON error message to come through.

**Comment by rosibaj** [comment]
-  should return a 401/403 regardless of why the token is invalid
