### ISSUE TITLE
Technical Architecture SONG 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/SONG#465]
Song needs to be able to support different modes of identification. For example ICGC and ARGO have both needed implementations.

Develop technical architecture specifying the integration of different "modes", "configs", "id services" etc.

- [ ] Define the identification method (locally or id server) 
- [ ] Define how to include/exclude ids

**Comment by rtisma** [comment]
scope change, since we will be combining id generation and QC analysis into one step called, entity processing.

**Comment by rosibaj** [comment]
https://wiki.oicr.on.ca/login.action?os_destination=%2Fpages%2Fviewpage.action%3FspaceKey%3Dicgcargotech%26title%3DTechnical%2BArchitecture%2B-%2BConfigurable%2BID%2BServer&permissionViolation=true

**Comment by rosibaj** [comment]
Update:  THIS IS CORRECT: https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=SPI+Interface+for+Processing+Entities+-+Technical+Architecture
