### ISSUE TITLE
Release Dynamic Song + client 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/SONG#485]
Vincent needs to be able to access the latest version of song + song-client, with the dynamic schemas.  

For the scope of this ticket:
- Documentation does not need to be included, with the exception of the swagger docs that we already have
-  We don't need to worry about making sure it gets to artifactory for download or docs explaining everything
- We do need to be able to distribute dockers of song + song-client to Vincent

**Comment by rtisma** [comment]
Here arre the release notes for 2.2.0
https://github.com/overture-stack/SONG/releases/tag/2.2.0

Here are the docker song-client instructions
https://github.com/overture-stack/SONG/blob/develop/README.md#docker-song-client
