### ISSUE TITLE
Song Accepts Expired API-Keys

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/SONG#585]
**Steps to Reproduce**
1. Get/make an expired API-Key from ARGO-QA EGO
2. Use a request that should require authentication ( Create a Study/Upload a Payload)
3. See the request go through

## Expected Behaviour
When a token is expired, it should return the not authorized err

## Exit Criteria for this ticket
- [ ]  Make sure Song (and Score) do not allow usage of an expired token
- [x] Verify if this is an issue with the DCC deployment.  Do this by testing with an expired dcc token and trying to download controlled data from score. If it is an issue, please create a ticket.

**Comment by rosibaj** [comment]
Verified that DCC is not an issue

**Comment by akachru-github** [comment]
Simulate by revoking a token.

**Comment by KevinFHartmann** [comment]
I didn't have any luck reproducing this bug. :-( 

I tried submitting an upload to SONG; it worked. Then I revoked the token using the portal api -- submissions then immediately failed.

The revoked token worked for SCORE; I wanted an hour and a few minutes, and tried again -- the upload then failed. I used the new token -- upload succeeded. 

Placing it into a blocked status until Rosi is back on Monday.

**Comment by rosibaj** [comment]
@KevinFHartmann this cannot be simulated by REVOKING the token - it has to be EXPIRED

Look up this token on qa: 
- `92066829-998c-4aa2-9fc2-b6b241f63ff0`
- make sure REVOKED is set to FALSE 
- you can see the expiry date is in december. 
- you will be able to make requests with it.

**Comment by rosibaj** [comment]
@KevinFHartmann Can you do a release to `argo-dev` or `argo-qa` so that I can test this?
