### ISSUE TITLE
Modified and Created timestamps in Song payloads

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/SONG#589]
We need created & modified timestamps in the Song payload, so they can be indexed to help us determine when to start the embargo clock

These should be added to the `base schema`, not the dynamic portion.

**Comment by akachru-github** [comment]
Embargo clock starts when molecular analysis done and clinical data available, those two dates start the embargo clock. 

This will be critical piece to starting the embargo clock. 

Further discussion required on embargo clock logic.

**Comment by rosibaj** [comment]
this is done.
