### ISSUE TITLE
RDPC Backups: Update SONG/Intermediate SONG/Submission SONG backup to use NFS instead of Object storage

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/SONG#628]
- SONG was being backed up in object storage. We have since made the decision to standardize all backups to NFS to make storage and replication to offsite storage less complex. 
- Details on RDPC backups: https://wiki.oicr.on.ca/display/icgcargotech/Backups+and+Restoration#BackupsandRestoration-Whereisitbeingbackedupandhowlongisitbeingkeptfor

@henro001  and @jmimico can field questions if you have any!

Song/Score, Intermediate Song/Score, Submission Song/Score:
- [x] Backup
- [ ] Confirm manual restore
- [ ] documentation for backup / manual restore

Song instances to backup in scope of this ticket:
**rdpc-dev:**
- [x] intermediate-song
- [x] submission-song
- [x] song
**rdpc-qa:**
- [x] intermediate-song
- [x] submission-song
- [x] song
**rdpc-prod:**
- [x] intermediate-song
- [x] submission-song
- [x] song

**Comment by akachru-github** [comment]
@rtisma , I can't remember if you got to this or not?
cc. @jmimico , @henro001 , @yalturmes

**Comment by yalturmes** [comment]
Updated description to include helm song instances to backup.

**Comment by akachru-github** [comment]
Working through installing vault helm charts for rdpc dev, qa and prod to normalize the postgress backup boiler plate.

**Comment by yalturmes** [comment]
Progress update:
* Backups for all RDPC SONG instances configured and validated
* Pull requests with changes for SONG backup configurations created

**Comment by rosibaj** [comment]
Confirmed with a restore on Dec 14 2020

**Comment by akachru-github** [comment]
Update: 
SONG backups recovery has been tested successfully in the DEV environment.
On high level the process looks like this:

1. Take SONG psql backup before starting recovery testing
2. Stop SONG server instance (scale number of replicas to 0)
3. Rename old postgres DB to something else (song_old) without deleting pod
4. Create a new empty psql DB with the original name SONG application expects (song)
5. Recover psql db from backup to the newly created empty DB
6. Start SONG server instance
7. Confirm SONG pods started
8. Confirm song service ingress address is responsive
9. Confirm list of studies can be retrieved from SONG ingress URL

All the testing was done against a regular SONG instance (not submission nor intermediate) in rdpc-collab-dev
https://song.rdpc-dev.cancercollaboratory.org/studies/all

**Comment by yalturmes** [comment]
Wiki page with documentation on PSQL backup/recovery has been updated:
https://wiki.oicr.on.ca/pages/viewpage.action?pageId=146836074
