### ISSUE TITLE
Add Dates to to Song Analysis

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/SONG#675]
## Expected Outcome 
- [ ] When /submit endpoint is used, the `createdate` and `updateddate` is correctly populated in the anlysis
- [ ] When /studies/{studyId}/analysis/{analysisId}  endpoint is used, the `updateddate` is correctly populated in the analysis
- [ ] When /publish endpoint is FIRST used, the `publishdate` is correctly populated in the analysis
- [ ] When /publish endpoint is otherwise used, the `LASTpublishdate` is correctly populated in the analysis
- [ ] When /supress endpoint is used the `updateddate` is correctly populated in the analysis

**Comment by joneubank** [comment]
https://github.com/overture-stack/SONG/pull/684

**Comment by rosibaj** [comment]
Add dates as UTC Standard
