### ISSUE TITLE
BUG - Update Endpoint is not recording Updated Date

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/SONG#691]
The update endpoint  [PUT/studies/{studyId}/analysis/{analysisId}](https://song.rdpc-qa.cancercollaboratory.org/swagger-ui.html#/Analysis/updateAnalysisUsingPUT) is not changing the UpdatedDate in analysis
```
curl --location --request GET 'https://song.rdpc-dev.cancercollaboratory.org/studies/TEST-CA/analysis/25d0e9a5-730b-45c5-90e9-a5730b95c5bf' \
```

![image](https://user-images.githubusercontent.com/15824252/97898286-a9752200-1d05-11eb-986d-49092c7f20e5.png)

## Expected Behaviour 
UpdatedDate should change to the date when it is  updated.

**Comment by rtisma** [comment]
The updateDate should be updated in this method:
https://github.com/overture-stack/SONG/blob/develop/song-server/src/main/java/bio/overture/song/server/service/analysis/AnalysisServiceImpl.java#L152-L184

**Comment by joneubank** [comment]
@rtisma Updated Date is handled by spring. Any changes to the Analysis entity will result in a change.  What method was used to perform the update?

**Comment by rtisma** [comment]
@joneubank the Analysis DB entity is actually not updated. Instead, the current AnalysisData DB entity is `disassociated` causing it to be removed, and the new AnalysisData DB entity is `associated` causing it to point to the parent AnalysisId. For this reason, the updatedAt field on the Analysis DB entity must be manually set. So the Analysis DB entity records updatedAt timestamp when changes are made to the AnalysisData portion.

@rosibaj  in regards to updateFiles endpoint: https://song.rdpc.cancercollaboratory.org/swagger-ui.html#/File/updateUsingPUT
if an fileUpdate actually happens, does this affect the Analysis's updatedAt field? I believe it should not, but instead, the file entity has its own createdAt and updatedAt timestamps.

**Comment by rtisma** [comment]
This confusion is a byproduct of using DTOs as DAOs, a mistake Im paying for now :joy:

**Comment by rosibaj** [comment]
> if an fileUpdate actually happens, does this affect the Analysis's updatedAt field? I believe it should not, but instead, the file entity has its own createdAt and updatedAt timestamps.

@rtisma checked, and this `does not` change the updatedDate on an analysis: 

Updated an UNPUBLISHED file object: 
![image](https://user-images.githubusercontent.com/15824252/97907231-f3b0d000-1d12-11eb-90da-47094f27a511.png)

Looking at that analysis now, the `updatedDate` is `not` changes: 
![image](https://user-images.githubusercontent.com/15824252/97907424-438f9700-1d13-11eb-80a8-9e4de6dd164c.png)

**Comment by rosibaj** [comment]
@rtisma in regards to your question of  what `should` this do, is there really a large case to check individual object created/updated dates?  The majority of the time these timestamps will be the exact same as the analysis creation date. I would assume that if you had those individual dates on file objects, I would `still` expect the analysis `updatedDate` to change as when i retrieve the full body of the analysis, it looks different overall before and after the file object update.

**Comment by rosibaj** [comment]
```
curl --location --request PUT 'https://song.rdpc-dev.cancercollaboratory.org/studies/TEST-CA/analysis/25d0e9a5-730b-45c5-90e9-a5730b95c5bf' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <<<secret value>>>' \
--data-raw '{
    "analysisType": {
        "name": "variantCall"
    },
    "info": {
        "description": "ROSI IS CHANGING THIS TO TEST IF IT UPDATES CORRRRRECTLY!"
    },
    "experiment": {
        "variantCallingTool": "silver bullet",
        "matchedNormalSampleSubmitterId": "sample_x24_11a"
    }
}'
```

**Comment by rosibaj** [comment]
Attempted testing in Overture QA- appears no different:

**Comment by akachru-github** [comment]
@rosibaj , confirmed with @joneubank that the above feedback was fixed on friday.

**Comment by rosibaj** [comment]
Checked on overture-qa: 
- update endpoint it now showing the updated date correctly
![image](https://user-images.githubusercontent.com/15824252/100250164-5d378f00-2f0b-11eb-9d8b-40a6376ad1bd.png)
