### ISSUE TITLE
Provision Hashicorp Vault instances in RDPC envs

### ISSUE THREAD

**Issue by yalturmes** [overture-stack/SONG#701]
Deploy and configure Hashicorp Vault instances for the following cluster envs:
- [x] RDPC DEV/QA
- [x] RDPC PROD

At present these vault instances are required and blocking psql backup charts configuration for SONG instances. The psql backup chart that's been used for all other psql instances so far depends on availability of Vault to leverage secrets management.
In future these vault instances can also be used for secrets management in other RDPC applications.

Clean-up tasks:
- [ ] document Vault helm chart installation process
- [ ] Update argo-vault meta-chart repository

**Comment by yalturmes** [comment]
Progress update:
* Helm chart that was used in Argo Vault deployments could not be re-used as is due to deprecation of subcharts used
* Vault helm chart has been updated to use official up-to-date vault and consul repositories and installation process successfully tested on lab environment
* Vault helm chart has been deployed on RDPC dev/qa cluster.

Ticket scope has been extended:
* document Vault helm chart installation process
* Update argo-vault meta-chart repository

**Comment by yalturmes** [comment]
Progress update:
* Vault helm chart has been deployed on RDPC prod cluster

**Comment by yalturmes** [comment]
Status update:
* PR with Vault helm chart values for RDPC dev and prod created
* PR with updated argo-vault helm chart created

**Comment by akachru-github** [comment]
Some alerts are being trigggered for this in production. Will create a separate issue for this. 
This was initially deployed to support backups for Song instances. This does not effect those backups.
