### ISSUE TITLE
Tag and deploy song version to ARGO QA 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/SONG#702]
- Tag Song for release
- update dev version 
- complete migration in QA and deploy. 
- test and confirm working before prod deploy

**Comment by rtisma** [comment]
In addition to release song, the following is needed:
1. update https://github.com/overture-stack/helm-charts/tree/master/song with the configs and update helm chart version
2. after 1 is merged, in the chart-server repo, follow these instructions https://github.com/overture-stack/charts-server/blob/master/README.md
3. update values:
    https://github.com/icgc-argo/overture-infra/tree/master/helm/song
    https://github.com/icgc-argo/rdpc-infra/tree/master/helm/intermediate-song
    https://github.com/icgc-argo/rdpc-infra/tree/master/helm/song
    https://github.com/icgc-argo/rdpc-infra/tree/master/helm/submission-song
4. in https://jenkins.qa.cancercollaboratory.org/job/Overture.bio/job/provision/job/helm/  deploy song.overture-qa and song.overture-staging with the new chart version
5. in https://jenkins.rdpc-dev.cancercollaboratory.org/job/provision/job/manual-provision/ deploy
    song.rdpc-collab-dev
    intermediate-song.rdpc-collab-dev
    submission-song.rdpc-collab-dev
    song.rdpc-collab-qa
    intermediate-song.rdpc-collab-qa
    submission-song.rdpc-collab-qa

**Comment by rosibaj** [comment]
Verified release on prod song; retrieved LUCA-KR data from all analysis endpoint and saw the expected data + data format.
