### ISSUE TITLE
BUG -  helm chart needs conditionals updates

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/SONG#707]
Song chart has a bug (its missing conditionals against run profile) requiring manual hand holding to get it deployed

Here is an example of how to check what run profiles are in use and then conditionally require those env vars: https://github.com/icgc-argo/charts/blob/master/workflow-management/templates/deployment.yaml#L76-L97

Song's chart needs the same thing here: https://github.com/overture-stack/helm-charts/blob/master/song/templates/deployment.yaml#L112

This manifested in production for intermediate-song  requiring client credentials config for ICGC score even though it didn't have the run profile enabled to use it.

**Comment by andricDu** [comment]
New chart version: 0.11.0
Tested in dev.
Helm values updated for dev, qa, and prod.
