### ISSUE TITLE
BUG - Internal Service Error on Regular Expression instead of Schema Error 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/SONG#729]
## Description
- Uploaded data to Cancgogen,  and Song was throwing a `Internal Service Error` 
![image](https://user-images.githubusercontent.com/15824252/132018550-720be688-3a8b-4982-915f-12b67e0365a2.png)

After troubleshooting, the field that was causing this issue was narrowed down to the `breadth_of_coverage` field.  The regex expected 2 numbers, but `100%` was submitted.

This line:  https://github.com/cancogen-virus-seq/metadata-schemas/blob/e77496cda3e8c179b263be3e68b2cd8ea3dfc280/schemas/consensus_sequence.json#L814

Example data to use with this schema to replicate error:
[ABerrors-original.txt](https://github.com/overture-stack/SONG/files/7106458/ABerrors-original.txt)
[payload.txt](https://github.com/overture-stack/SONG/files/7106467/payload.txt)

## Expected Behaviour

Song should throw the expected Schema validation error saying the regex isn't valid, not an internal server error 

## Your Environment
- Cancogen Dev/Prod 
- schema version for song attached above

**Comment by leoraba** [comment]
Code fixed to return a 400 HTTP error code with the specific schema violation error.
