### ISSUE TITLE
Update Permissible values in the Song base schema `fileType` by adding `TXT`

### ISSUE THREAD

**Issue by lindaxiang** [overture-stack/SONG#741]
The current allowed fileType list is:
```
        "fileType": {
          "type": "string",
          "enum": [
            "FASTA",
            "FAI",
            "FASTQ",
            "BAM",
            "BAI",
            "VCF",
            "TBI",
            "IDX",
            "XML",
            "TGZ",
            "CRAM",
            "CRAI"
          ]
        }
```
We need to add `TXT` to this list to support new fileType generated by RNA-Seq alignment workflow

**Comment by joneubank** [comment]
add changes to base schema as migration to existing base schema: 
https://github.com/overture-stack/SONG/tree/develop/song-server/src/main/resources/db/migration
