### ISSUE TITLE
BUG - SONG `Update` can update the analysis when it is in `PUBLISHED` state?

### ISSUE THREAD

**Issue by lindaxiang** [overture-stack/SONG#742]
## Description
The SONG analysis `Update` can directly update the analysis content without turning the analysis into `Unpublished` state. Not sure if this is the designed behaviour?

## Expected Behaviour
The analysis should be `UNPUBLISHED` state when using `update` API endpoints. 

## Actual Behaviour
The analysis can be `update` directly when the analysis in `PUBLISHED` state.

## Steps to Reproduce

Example:
song API: https://song.rdpc-qa.cancercollaboratory.org/swagger-ui.html
analysisId: d52da6eb-e526-487c-ada6-ebe526d87cc2
studyId: TCRB-CA
analysis_url: https://song.rdpc-qa.cancercollaboratory.org/studies/TCRB-CA/analysis/d52da6eb-e526-487c-ada6-ebe526d87cc2

1. Go to https://song.rdpc-qa.cancercollaboratory.org/swagger-ui.html
2. Click on `Analysis` and `UpdateAnalysis`
3. Fill in `Authorization`, `analysisId`, `studyId`
4. Fill `updateAnalysisRequest` using the following content
```
{
  "analysisType":{
    "name":"variant_calling"
  },
  "workflow":{
    "inputs":[
      {
        "analysis_type":"sequencing_alignment",
        "tumour_analysis_id":"d5f2bbc1-8fed-4b8b-b2bb-c18fedbb8be4"
      },
      {
        "analysis_type":"sequencing_alignment",
        "normal_analysis_id":"9f847b3c-6c98-427c-847b-3c6c98527c65"
      }
    ],
    "run_id":"wes-973b08fc959846c7996879003e222502",
    "session_id":"5c7f3899-540d-4c62-9b43-10e5b995c714",
    "genome_build":"GRCh38_hla_decoy_ebv",
    "workflow_name":"Sanger WXS Variant Calling",
    "workflow_version":"3.1.6-3.6.0",
    "workflow_short_name":"sanger-wxs"
  },
  "experiment":{
    "platform":"ILLUMINA",
    "experimental_strategy":"WXS"
  },
  "variant_class":"Somatic"
}
```
5. Click `Execute` and you will receive `200` without errors.

## Your Environment

SONG API endpoints:
`update`: https://song.rdpc-qa.cancercollaboratory.org/swagger-ui.html#/Analysis/updateAnalysisUsingPUT
`unpublish`: https://song.rdpc-qa.cancercollaboratory.org/swagger-ui.html#/Analysis/unpublishAnalysisUsingPUT 
`publish`: https://song.rdpc-qa.cancercollaboratory.org/swagger-ui.html#/Analysis/unpublishAnalysisUsingPUT

**Comment by akachru-github** [comment]
@joneubank , @Buwujiu , can either of you confirm whether this ticket is capturing expected behaviour?

**Comment by sifavahora** [comment]
This is the expected behavior for Song. hence closing the ticket.
