### ISSUE TITLE
Change the validation rule in SONG base schema for field `matchedNormalSubmitterSampleId`

### ISSUE THREAD

**Issue by lindaxiang** [overture-stack/SONG#750]
Since most RNA-Seq samples do NOT have matched normal samples, we need to change the validation rule in SONG base schema for field `matchedNormalSubmitterSampleId` as following:
- `matchedNormalSubmitterSampleId` is required field under `samples`
- If `tumourNormalDesignation` is Normal, the field must filled with `null`
- if `tumourNormalDesignation` is Tumour, the field could be `null` or filled in string with format `"$ref":"#/definitions/common/submitterId"` 

FYI: Current validation rule for field `matchedNormalSubmitterSampleId` in SONG base schema is:
- `matchedNormalSubmitterSampleId` is required field under `samples`
- If `tumourNormalDesignation` is Normal, the field must filled with `null`
- if `tumourNormalDesignation` is Tumour, the field must be filled in string with format `"$ref":"#/definitions/common/submitterId"` 

Related schema definition is
```
{
  "if":{
    "properties":{
      "specimen":{
        "properties":{
          "tumourNormalDesignation":{
            "const":"Tumour"
          }
        }
      }
    }
  },
  "then":{
    "properties":{
      "matchedNormalSubmitterSampleId":{
        "$ref":"#/definitions/common/submitterId"
      }
    },
    "required":[
      "matchedNormalSubmitterSampleId"
    ]
  },
  "else":{
    "properties":{
      "matchedNormalSubmitterSampleId":{
        "const":null
      }
    },
    "required":[
      "matchedNormalSubmitterSampleId"
    ]
  }
}


```

**Comment by lindaxiang** [comment]
@Buwujiu 
For SONG base schema, current `sample_type` has the following enum:
```
Amplified DNA
ctDNA
Other DNA enrichments
Other RNA fractions
polyA+ RNA
Ribo-Zero RNA
Total DNA
Total RNA
```
We can refactor the above rule as:
- `matchedNormalSubmitterSampleId` is required field under `samples`
- If `tumourNormalDesignation= Normal`, the field must filled with `null`
- if `tumour_normal_designation=Tumour` and `sample_type` has values in 
```
Other RNA fractions
polyA+ RNA
Ribo-Zero RNA
Total RNA
```
the field could be `null` or filled in string with format `"$ref":"#/definitions/common/submitterId"` 
- if `tumourNormalDesignation=Tumour` and `sample_type` has values in 
```
Amplified DNA
ctDNA
Other DNA enrichments
Total DNA
```
the field must be filled in string with format `"$ref":"#/definitions/common/submitterId"` 

We can create separate tickets for its potentially effects to the donor-aggregator.

**Comment by akachru-github** [comment]
@Buwujiu to assess impact on downstream services before implementation. 
Potential impacts to donor agg.
