### ISSUE TITLE
Add New Permissible Value to "specimen_type"

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/SONG#765]
Add "Malignant neoplasm without specification of site" to permissible enum list of `specimen_type`

Blocks this ticket: https://github.com/icgc-argo/argo-dictionary/issues/340

See that ticket for context

Requires Dev work as this is a change to the base SONG schema, NOT the dynamic portion

**NOTE:** Takes priority over RNA-Seq, Clinical Exceptions features

**Comment by b-f-chan** [comment]
Agreed with @hknahal no immediate urgency this sprint, as she still needs to do some work for dictionary 1.14, so we can delay this SONG fix to next sprint

**Comment by b-f-chan** [comment]
Base schema needs changing and enum added

**Comment by b-f-chan** [comment]
@Buwujiu - Was this tested in QA?

**Comment by b-f-chan** [comment]
Defer to dictionary v.1.15 release / L release for platform

**Comment by b-f-chan** [comment]
SONG fix is done, need PR review from @Buwujiu before this ticket can move forward

**Comment by b-f-chan** [comment]
@Buwujiu to attach new PR to same ticket that includes the script that fixes the missing function

**Comment by b-f-chan** [comment]
Edmund tested and no issues, moving to Awaiting Release

**Comment by Buwujiu** [comment]
Based on @hknahal 's comment: https://github.com/icgc-argo/argo-dictionary/issues/340#issuecomment-1090829348, we need to add `Tumour - unknown if derived from primary or metastatic` to specimen_type, NOT `Malignant neoplasm without specification of site`. Created ticket https://github.com/overture-stack/SONG/issues/775 for replacing enum.

**Comment by Buwujiu** [comment]
ticket in prod, closing.
