### ISSUE TITLE
Test & Verify DELETE Endpoints

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/SONG#766]
As part of the analysis done for , and the related SOP (https://wiki.oicr.on.ca/pages/viewpage.action?pageId=150638363) it was found that some of the DELETE endpoint behaviours have not been fully tested/verified

This ticket is to test these specific endpoints and make sure they work as expected:

- DELETE /studies/{studyId}/samples/{ids}
- DELETE /studies/{studyId}/specimens/{ids} 
- DELETE /studies/{studyId}/donors/{ids}

**Comment by b-f-chan** [comment]
Already tested in QA - But endpoint does not work - Need Dev to investigate

**Comment by Buwujiu** [comment]
questions for @lindaxiang : are these endpoints working in prod or qa?
DELETE /studies/{studyId}/specimens/{ids}
DELETE /studies/{studyId}/donors/{ids}

reminder for @hknahal : Please follow up with LUCA_KR on whether they want to delete metadata from song or clinical data?

**Comment by lindaxiang** [comment]
@b-f-chan @Buwujiu 
I also tested the DELETE /studies/{studyId}/samples/{ids} endpoint in Prod for the following study/sample
```
studyId: TEST-INTL
sampleId: SA611445
songURL: https://song.rdpc-qa.cancercollaboratory.org/
```
Steps to re-produce:
1. Call endpoint: GET `/studies/TEST-INTL/samples/SA611445` or URL: 
```
https://song.rdpc.cancercollaboratory.org/studies/TEST-INTL/samples/SA611445
```
Here is the returned response:
```
{
"sampleId": "SA611445",
"specimenId": "SP211445",
"submitterSampleId": "donor1_sample1_id",
"matchedNormalSubmitterSampleId": "donor1_sample2_id",
"sampleType": "Total RNA"
}
```
2. delete the sample by call: DELETE /studies/{studyId}/samples/{ids}. ----- Failed with 500 error:
```
 cache-control: no-cache, no-store, max-age=0, must-revalidate 
 date: Wed, 27 Jul 2022 19:57:01 GMT 
 expires: 0 
 pragma: no-cache 
 strict-transport-security: max-age=15724800; includeSubDomains 
 x-content-type-options: nosniff 
 x-frame-options: DENY 
 x-xss-protection: 1; mode=block 
```
Basically get back the same behaviour as what we saw in QA. Need Dev to investigate whether this endpoint has been implemented or not.

**Comment by b-f-chan** [comment]
@lindaxiang tested and got 500 error in prod, not sure if related to token or she doesn't have access due to permissions, so need dev to investigate; this was done on the test program

We will assign a developer to investigate

**Comment by Buwujiu** [comment]
Might be related to this https://github.com/overture-stack/SONG/issues/776, assigning to @UmmulkiramR for reference.

**Comment by Buwujiu** [comment]
@joneubank fixed the access denied issue in prod song during Loki release, however the delete endpoints are still broken in song QA and Prod. I tested delete samples in both environments, didn't get access denied error, but song returned 500 and failed to delete samples. Will close this issue and create a new ticket for tracking broken delete endpoints.
