### ISSUE TITLE
Add parameters to GET endpoint  /studies/{studyId}/analysis/search/id 

### ISSUE THREAD

**Issue by sifavahora** [overture-stack/SONG#783]
We want to add the following parameters to the Get Endpoint: 
- submitterSampleId
- submitterDonorId
- submitterSpecimenId

**Comment by Buwujiu** [comment]
deployed to QA.

**Comment by Buwujiu** [comment]
@lindaxiang will help test in QA.

**Comment by Buwujiu** [comment]
Tested in Prod, working as expected!
