### ISSUE TITLE
Song-client and Song-server unit tests failing due to a Json parsing error

### ISSUE THREAD

**Issue by anncatton** [overture-stack/SONG#799]
Running command: mvn clean install
- with apache-maven-3.8.6; jdk-11.0.16
- with commit https://github.com/overture-stack/SONG/commit/3396c2ab5409c73640f792e98607e1570f0ae979
-  [ERROR] testListAnalysisTypes(bio.overture.song.client.HappyPathClientMainTest)  Time elapsed: 0.002 s  <<< ERROR!
com.fasterxml.jackson.core.JsonParseException:
Illegal character ((CTRL-CHAR, code 27)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (String)"\u001B[K\u001B[32m[

**Comment by leoraba** [comment]
Fixed Unit tests.
PRs releated:
[#797](https://github.com/overture-stack/SONG/pull/797)
[#811](https://github.com/overture-stack/SONG/pull/811)
