### ISSUE TITLE
BUG - Unauthorized Error when Creating An Analysis in SONG via Swagger UI

### ISSUE THREAD

**Issue by Azher2Ali** [overture-stack/SONG#853]
## Description
 When attempting to create an analysis through the Swagger UI at http://localhost:8080/swagger-ui.html#/Submit/submitUsingPOST, the response returned is a 401 Unauthorized error. This occurs despite using the access token provided in the credentials.txt file located at https://github.com/overture-stack/SONG/blob/develop/song-docker-demo/credentials.txt 

## Expected Behaviour
The analysis submission should successfully process without returning a 401 Unauthorized error when the correct access token is used.

## Actual Behaviour
The server returns a 401 Unauthorized response:

Code: 401
Details: Error: Unauthorized

## Steps to Reproduce

1. Run Song using the following instructions: https://github.com/overture-stack/SONG/blob/develop/song-server/README.md
2. Navigate to the Submit section and select the submitUsingPOST endpoint (http://localhost:8080/swagger-ui.html#/Submit)
3 Use the access token from the credentials.txt file located at https://github.com/overture-stack/SONG/blob/develop/song-docker-demo/credentials.txt
4. Submit a request to create an analysis.
5. Observe that the server returns a 401 Unauthorized response.

**Comment by MitchellShiell** [comment]
Your steps to reproduce are a bit vague, how are you running Song, from docker or source?

**Comment by Azher2Ali** [comment]
> Your steps to reproduce are a bit vague, how are you running Song, from docker or source?

I'm running SONG from docker

**Comment by MitchellShiell** [comment]
Correct me if i am wrong but the instructions you linked are running it using mvn. If the intention is to run via docker than [this updated doc ](https://github.com/overture-stack/SONG/blob/a45495de7813f2505718000872b225e5d281715f/docs/operation/operation.md) written by Leo should be better use.
